version: "3.8"

services:
  user-web:
    build:
      context: .
      dockerfile: packages/user-web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REACT_APP_ENV=prod
    restart: unless-stopped
    container_name: gam_user_web

  backstage:
    build:
      context: .
      dockerfile: packages/backstage/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - REACT_APP_ENV=prod
    restart: unless-stopped
    container_name: gam_backstage
